class Autogenerated {
  int? total;
  int? count;
  List<Data>? data;

  Autogenerated({this.total, this.count, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    count = json['count'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['total'] = total;
    data['count'] = count;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? submissionId;
  String? submissionUrl;
  String? submissionTitle;
  String? permalink;
  String? author;
  String? created;
  String? timestamp;

  Data(
      {this.submissionId,
        this.submissionUrl,
        this.submissionTitle,
        this.permalink,
        this.author,
        this.created,
        this.timestamp});

  Data.fromJson(Map<String, dynamic> json) {
    submissionId = json['submission_id'];
    submissionUrl = json['submission_url'];
    submissionTitle = json['submission_title'];
    permalink = json['permalink'];
    author = json['author'];
    created = json['created'];
    timestamp = json['timestamp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['submission_id'] = this.submissionId;
    data['submission_url'] = this.submissionUrl;
    data['submission_title'] = this.submissionTitle;
    data['permalink'] = this.permalink;
    data['author'] = this.author;
    data['created'] = this.created;
    data['timestamp'] = this.timestamp;
    return data;
  }
}